### ISSUE TITLE
Instructions for use on adafruit Trinket M0

### ISSUE THREAD

**Issue by wicksand420** [atlas44/sam-fusee-launcher#1]
Hi @atlas44 I was wondering if you could give some instruction for use for sam-fusee-launcher and adafruit M0? Any help you can lend would be greatly appreciated. Thank you.

**Comment by bad1dea** [comment]
yes ditto.. i just ordered a few and some breakout boards too.

**Comment by X41** [comment]
The process is pretty simple
[set up your arduino enviroment for the trinket m0,](https://learn.adafruit.com/add-boards-arduino-v164/setup) rename the .cpp file to .ino, open it in the arduino IDE, flash it and you're done 

the payload is stored as a hex array in `payload.h` and contains the fusee.bin by default. you can replace that with a payload of your choice, hekate for example. make sure you adjust `FUSEE_BIN_SIZE` too


the "official" way is to use platform.io i guess, but i never got that to work and most people are more familiar with the arduino IDE anyways

**Comment by wicksand420** [comment]
Much appreciated, I saw what you where doing on twitter and I'm planning on doing the same.

**Comment by X41** [comment]
glad to hear that ^^
feel free to message me if you have more questions

**Comment by wicksand420** [comment]
@X41 what all do i needed to flash this to the m0, I get an error compiling #include <usb.h>
Do other files have to be in the lib folder? also, when importing the project in arduino ide it places the main.ino inside of a main folder, is this my problem? can you show me your folder structure so i know i'm not making any mistakes?

**Comment by Ninoh-FOX** [comment]
@wicksand420 Edit <usb.h> for <Usb.h>

**Comment by wicksand420** [comment]
@Ninoh-FOX that was the problem, someone should make a note for those using the trinket m0 board
